export const FETCHING_PLANT = 'FETCHING_PLANT';
export const FETCHED_PLANT = 'FETCHED_PLANT';
export const FETCH_PLANT_ERROR = 'FETCH_PLANT_ERROR';
export const FETCHING_PLANTS = 'FETCHING_PLANTS';
export const FETCHED_PLANTS = 'FETCHED_PLANTS';
export const FETCH_PLANTS_ERROR = 'FETCH_PLANTS_ERROR';
export const VIEWED_PLANT = 'VIEWED_PLANT';

