
export const ADDING_PLANT = 'ADDING_PLANT';
export const ADDED_PLANT = 'ADDED_PLANT';
export const ADD_PLANT_ERROR = 'ADD_PLANT_ERROR';
export const REMOVING_PLANT = 'REMOVING_PLANT';
export const REMOVED_PLANT = 'REMOVED_PLANT';
export const REMOVE_PLANT_ERROR = 'REMOVE_PLANT_ERROR';
export const MOVING_PLANT = 'MOVING_PLANT';
export const MOVED_PLANT = 'MOVED_PLANT';
export const MOVE_PLANT_ERROR = 'MOVE_PLANT_ERROR';
