export const ADDING_PLANT = 'ADDING_PLANT';
export const ADDED_PLANT = 'ADDED_PLANT';
export const ADD_PLANT_ERROR = 'ADD_PLANT_ERROR';
export const REMOVING_PLANT = 'REMOVING_PLANT';
export const REMOVED_PLANT = 'REMOVED_PLANT';
export const REMOVE_PLANT_ERROR = 'REMOVE_PLANT_ERROR';
export const MOVING_PLANT = 'MOVING_PLANT';
export const MOVED_PLANT = 'MOVED_PLANT';
export const MOVE_PLANT_ERROR = 'MOVE_PLANT_ERROR';
export const FETCHING_GARDEN = 'FETCHING_GARDEN';
export const FETCHED_GARDEN = 'FETCHED_GARDEN';
export const FETCHED_GARDEN_ERROR = 'FETCHED_GARDEN_ERROR';
export const ADDED_GARDEN = 'ADDED_GARDEN';
export const ADDING_GARDEN = 'ADDING_GARDEN';
export const ADD_GARDEN_ERROR = 'ADD_GARDEN_ERROR';
export const SAVING_GARDEN = 'SAVING_GARDEN';
export const SAVED_GARDEN = 'SAVED_GARDEN';
export const SAVE_GARDEN_ERROR = 'SAVE_GARDEN_ERROR';
export const DELETING_GARDEN = 'DELETING_GARDEN';
export const DELETED_GARDEN = 'DELETED_GARDEN';
export const DELETE_GARDEN_ERROR = 'DELETE_GARDEN_ERROR';
<<<<<<< HEAD

export const Types = { PLANT: 'plant' };
=======
export const PLANT = 'PLANT';
>>>>>>> 1d1052aa769aebf5f99f6e5921dfd3efce947ff0
