export const SAVING_GARDEN = 'SAVING_GARDEN';
export const SAVED_GARDEN = 'SAVED_GARDEN';
export const SAVE_GARDEN_ERROR = 'SAVE_GARDEN_ERROR';
export const DELETING_GARDEN = 'DELETING_GARDEN';
export const DELETED_GARDEN = 'DELETED_GARDEN';
export const DELETE_GARDEN_ERROR = 'DELETE_GARDEN_ERROR';